name: Update KAP Leaderboard

on:
  schedule:
    - cron: "* * * * *"  # каждую минуту
  workflow_dispatch:      # ручной запуск

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-api-python-client google-auth

      - name: Run leaderboard script
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: python leaderboard.py
