name: Update KAP Leaderboard

# Оставляем только ручной запуск
on:
  workflow_dispatch:

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-api-python-client google-auth

      - name: Run leaderboard script
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          echo "=== START SCRIPT ==="
          python leaderboard.py
          echo "=== END SCRIPT ==="
